export const PROJECT_CREATE_REQUEST = "PROJECT_CREATE_REQUEST";
export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS";
export const PROJECT_CREATE_FAIL = "PROJECT_CREATE_FAIL";

//GETS THE PROJECTS OWNED BY THE LOGIN USER
export const PROJECT_GET_USERS_OWNED_REQUEST = "PROJECT_GET_USERS_OWNED_REQUEST";
export const PROJECT_GET_USERS_OWNED_SUCCESS = "PROJECT_GET_USERS_OWNED_SUCCESS";
export const PROJECT_GET_USERS_OWNED_FAIL = "PROJECT_GET_USERS_OWNED_FAIL";

//adds a list item to the project board
export const PROJECT_BOARD_LIST_ADD_REQUEST = "PROJECT_BOARD_LIST_ADD_REQUEST";
export const PROJECT_BOARD_LIST_ADD_SUCCESS = "PROJECT_BOARD_LIST_ADD_SUCCESS";
export const PROJECT_BOARD_LIST_ADD_FAIL = "PROJECT_BOARD_LIST_ADD_FAIL";
